package core

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/getsentry/sentry-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// echo v5 answers routing failures with its own sentinels, which are no longer
// *echo.HTTPError. Read wrongly they arrive as "500 internal server error" —
// so this pins the shape a client actually sees.
func TestHTTP_routingFailuresKeepTheFrameworkErrorShape(t *testing.T) {
	app := newTestApp(t)
	e := NewHTTPServer(app, nil)
	e.GET("/ok", func(c IHTTPContext) error { return c.JSON(http.StatusOK, "ok") })

	cases := []struct {
		name, method, path string
		status             int
		message            string
	}{
		{"no such route", http.MethodGet, "/nope", http.StatusNotFound, "Not Found"},
		{"wrong method", http.MethodPost, "/ok", http.StatusMethodNotAllowed, "Method Not Allowed"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			rr := httptest.NewRecorder()
			e.ServeHTTP(rr, httptest.NewRequest(tc.method, tc.path, nil))

			require.Equal(t, tc.status, rr.Code)
			var body map[string]any
			require.NoError(t, json.Unmarshal(rr.Body.Bytes(), &body))
			assert.Equal(t, "HTTP_ERROR", body["code"])
			assert.Equal(t, tc.message, body["message"])
		})
	}
}

// A URL that does not exist is not an incident. Scanners walk the internet all
// day; before this they filled the Sentry project on their own.
func TestHTTP_routingFailuresAreNotIncidents(t *testing.T) {
	app, rec := newSentryApp(t, map[string]string{"SENTRY_ENABLE_TRACING": "true"})
	e := NewHTTPServer(app, nil)
	e.GET("/ok", func(c IHTTPContext) error { return c.JSON(http.StatusOK, "ok") })

	rr := httptest.NewRecorder()
	e.ServeHTTP(rr, httptest.NewRequest(http.MethodGet, "/nope", nil))

	require.Equal(t, http.StatusNotFound, rr.Code)
	assert.Equal(t, 0, rec.Len(), "a 404 is the caller's mistake, not ours")

	// and the transaction says 404, not 200 — the status is known from the error
	// even though nothing had been written when the middleware unwound
	var tx *sentry.Event
	for _, ev := range rec.Events() {
		if ev.Type == "transaction" {
			tx = ev
		}
	}
	require.NotNil(t, tx)
	assert.Equal(t, "404", tx.Tags["http.status"])
}

func TestHTTP_corsDefaultsAndRestriction(t *testing.T) {
	app := newTestApp(t)

	open := NewHTTPServer(app, nil)
	open.GET("/ok", func(c IHTTPContext) error { return c.JSON(http.StatusOK, "ok") })
	assert.Equal(t, "*", originAllowedBy(open, "https://app.example.com"),
		"the framework's default has always been permissive; v5 has no DefaultCORSConfig to inherit it from")

	limited := NewHTTPServer(app, &HTTPOptions{AllowOrigins: []string{"https://allowed.example.com"}})
	limited.GET("/ok", func(c IHTTPContext) error { return c.JSON(http.StatusOK, "ok") })
	assert.Equal(t, "https://allowed.example.com", originAllowedBy(limited, "https://allowed.example.com"))
	assert.Empty(t, originAllowedBy(limited, "https://evil.example.com"))
}

func originAllowedBy(e *Server, origin string) string {
	req := httptest.NewRequest(http.MethodGet, "/ok", nil)
	req.Header.Set("Origin", origin)
	rr := httptest.NewRecorder()
	e.ServeHTTP(rr, req)
	return rr.Header().Get("Access-Control-Allow-Origin")
}

// A service behind a gateway that already logs every request should be able to
// stop writing the line twice — without giving up breadcrumbs or error
// reporting, which are their own switches.
type routeCtrl struct{}

func (routeCtrl) Pagination(c IHTTPContext) error { return c.JSON(http.StatusOK, "ok") }

// TestHTTP_accessLineNamesTheHandler covers what the access line's own source
// cannot: it is written after the handler has returned, so the frame is gone and
// "http_server.go:413" is all it could ever say.
func TestHTTP_accessLineNamesTheHandler(t *testing.T) {
	cases := []struct {
		name    string
		handler HandlerFunc
		want    string
	}{
		// how routes are registered in practice, and the case a file and line
		// cannot serve: Go compiles a method value into a wrapper reported as
		// "<autogenerated>:1"
		{"method value", routeCtrl{}.Pagination, "routeCtrl.Pagination"},
		{"closure", func(c IHTTPContext) error { return c.JSON(http.StatusOK, "ok") },
			"TestHTTP_accessLineNamesTheHandler"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var out strings.Builder
			env := mustEnv(t, nil)
			app, err := NewApp(env, WithLogger(NewLoggerTo(&out, env)))
			require.NoError(t, err)

			e := NewHTTPServer(app, nil)
			e.GET("/ok", tc.handler)
			e.ServeHTTP(httptest.NewRecorder(), httptest.NewRequest(http.MethodGet, "/ok", nil))

			assert.Contains(t, out.String(), tc.want, "the access line must say which handler served the request")
			assert.NotContains(t, out.String(), "-fm", "the generated wrapper's suffix is noise")
			assert.NotContains(t, out.String(), "mine-core/v2.", "the import path is the same for every route")
		})
	}
}

func TestHTTP_requestLogCanBeDisabled(t *testing.T) {
	cases := []struct {
		name string
		env  map[string]string
		opts *HTTPOptions
		want bool
	}{
		{"on by default", nil, nil, true},
		{"off by env", map[string]string{"LOG_REQUEST": "false"}, nil, false},
		{"off by option", nil, &HTTPOptions{DisableRequestLog: BoolPtr(true)}, false},
		{"option beats env", map[string]string{"LOG_REQUEST": "false"},
			&HTTPOptions{DisableRequestLog: BoolPtr(false)}, true},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var out strings.Builder
			env := mustEnv(t, tc.env)
			app, err := NewApp(env, WithLogger(NewLoggerTo(&out, env)))
			require.NoError(t, err)

			e := NewHTTPServer(app, tc.opts)
			e.GET("/ok", func(c IHTTPContext) error { return c.JSON(http.StatusOK, "ok") })
			e.ServeHTTP(httptest.NewRecorder(), httptest.NewRequest(http.MethodGet, "/ok", nil))

			assert.Equal(t, tc.want, strings.Contains(out.String(), "GET /ok 200"))
		})
	}
}
